import frappe


def execute():
	items = [
		{
		"allow_alternative_item": 0,
		"attributes": [],
		"auto_create_assets": 0,
		"barcodes": [],
		"country_of_origin": "Kenya",
		"create_new_batch": 0,
		"customer_code": "",
		"customer_items": [],
		"default_material_request_type": "Purchase",
		"delivered_by_supplier": 0,
		"description": "Rent Bill",
		"disabled": 0,
		"docstatus": 0,
		"doctype": "Item",
		"enable_deferred_expense": 0,
		"enable_deferred_revenue": 0,
		"end_of_life": "2099-12-31",
		"grant_commission": 1,
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"has_serial_no": 0,
		"has_variants": 0,
		"include_item_in_manufacturing": 1,
		"inspection_required_before_delivery": 0,
		"inspection_required_before_purchase": 0,
		"is_customer_provided_item": 0,
		"is_fixed_asset": 0,
		"is_item_from_hub": 0,
		"is_purchase_item": 1,
		"is_sales_item": 1,
		"is_stock_item": 0,
		"is_sub_contracted_item": 0,
		"item_code": "ITM-00001",
		"item_group": "Services",
		"item_name": "Rent Bill",
		"last_purchase_rate": 0.0,
		"lead_time_days": 0,
		"max_discount": 0.0,
		"min_order_qty": 0.0,
		"modified": "2022-10-04 14:29:25.696110",
		"name": "ITM-00001",
		"no_of_months": 0,
		"no_of_months_exp": 0,
		"opening_stock": 0.0,
		"over_billing_allowance": 0.0,
		"over_delivery_receipt_allowance": 0.0,
		"publish_in_hub": 0,
		"published_in_website": 0,
		"reorder_levels": [],
		"retain_sample": 0,
		"safety_stock": 0.0,
		"sample_quantity": 0,
		"shelf_life_in_days": 0,
		"standard_rate": 0.0,
		"stock_uom": "Nos",
		"supplier_items": [],
		"synced_with_hub": 0,
		"taxes": [],
		"total_projected_qty": 0.0,
		"uoms": [
		{
			"conversion_factor": 1.0,
			"parent": "ITM-00001",
			"parentfield": "uoms",
			"parenttype": "Item",
			"uom": "Nos"
		}
		],
		"valuation_method": "",
		"valuation_rate": 0.0,
		"variant_based_on": "Item Attribute",
		"weight_per_unit": 0.0,
		},
		{
		"allow_alternative_item": 0,
		"attributes": [],
		"auto_create_assets": 0,
		"barcodes": [],
		"country_of_origin": "Kenya",
		"create_new_batch": 0,
		"customer_code": "",
		"customer_items": [],
		"default_material_request_type": "Purchase",
		"delivered_by_supplier": 0,
		"description": "Electricity Services",
		"disabled": 0,
		"docstatus": 0,
		"doctype": "Item",
		"enable_deferred_expense": 0,
		"enable_deferred_revenue": 0,
		"end_of_life": "2099-12-31",
		"grant_commission": 1,
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"has_serial_no": 0,
		"has_variants": 0,
		"include_item_in_manufacturing": 1,
		"inspection_required_before_delivery": 0,
		"inspection_required_before_purchase": 0,
		"is_customer_provided_item": 0,
		"is_fixed_asset": 0,
		"is_item_from_hub": 0,
		"is_purchase_item": 1,
		"is_sales_item": 1,
		"is_stock_item": 0,
		"is_sub_contracted_item": 0,
		"item_code": "ITM-00002",
		"item_group": "Services",
		"item_name": "Electricity Bill",
		"last_purchase_rate": 0.0,
		"lead_time_days": 0,
		"max_discount": 0.0,
		"min_order_qty": 0.0,
		"modified": "2022-10-04 14:29:51.691150",
		"name": "ITM-00002",
		"no_of_months": 0,
		"no_of_months_exp": 0,
		"opening_stock": 0.0,
		"over_billing_allowance": 0.0,
		"over_delivery_receipt_allowance": 0.0,
		"publish_in_hub": 0,
		"published_in_website": 0,
		"reorder_levels": [],
		"retain_sample": 0,
		"safety_stock": 0.0,
		"sample_quantity": 0,
		"shelf_life_in_days": 0,
		"standard_rate": 0.0,
		"stock_uom": "Nos",
		"supplier_items": [],
		"synced_with_hub": 0,
		"taxes": [],
		"total_projected_qty": 0.0,
		"uoms": [
		{
			"conversion_factor": 1.0,
			"parent": "ITM-00002",
			"parentfield": "uoms",
			"parenttype": "Item",
			"uom": "Nos"
		}
		],
		"valuation_method": "",
		"valuation_rate": 0.0,
		"variant_based_on": "Item Attribute",
		"weight_per_unit": 0.0,
		},
		{
		"allow_alternative_item": 0,
		"attributes": [],
		"auto_create_assets": 0,
		"barcodes": [],
		"country_of_origin": "Kenya",
		"create_new_batch": 0,
		"customer_code": "",
		"customer_items": [],
		"default_material_request_type": "Purchase",
		"delivered_by_supplier": 0,
		"description": "Water Bill",
		"disabled": 0,
		"docstatus": 0,
		"doctype": "Item",
		"enable_deferred_expense": 0,
		"enable_deferred_revenue": 0,
		"end_of_life": "2099-12-31",
		"grant_commission": 1,
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"has_serial_no": 0,
		"has_variants": 0,
		"include_item_in_manufacturing": 1,
		"inspection_required_before_delivery": 0,
		"inspection_required_before_purchase": 0,
		"is_customer_provided_item": 0,
		"is_fixed_asset": 0,
		"is_item_from_hub": 0,
		"is_purchase_item": 1,
		"is_sales_item": 1,
		"is_stock_item": 0,
		"is_sub_contracted_item": 0,
		"item_code": "ITM-00003",
		"item_group": "Services",
		"item_name": "Water Bill",
		"last_purchase_rate": 0.0,
		"lead_time_days": 0,
		"max_discount": 0.0,
		"min_order_qty": 0.0,
		"modified": "2022-10-04 14:30:18.459249",
		"name": "ITM-00003",
		"no_of_months": 0,
		"no_of_months_exp": 0,
		"opening_stock": 0.0,
		"over_billing_allowance": 0.0,
		"over_delivery_receipt_allowance": 0.0,
		"publish_in_hub": 0,
		"published_in_website": 0,
		"reorder_levels": [],
		"shelf_life_in_days": 0,
		"standard_rate": 0.0,
		"stock_uom": "Nos",
		"supplier_items": [],
		"synced_with_hub": 0,
		"taxes": [],
		"total_projected_qty": 0.0,
		"uoms": [
		{
			"conversion_factor": 1.0,
			"parent": "ITM-00003",
			"parentfield": "uoms",
			"parenttype": "Item",
			"uom": "Nos"
		}
		],
		"valuation_method": "",
		"valuation_rate": 0.0,
		"variant_based_on": "Item Attribute",
		},
		{
		"allow_alternative_item": 0,
		"attributes": [],
		"auto_create_assets": 0,
		"barcodes": [],
		"country_of_origin": "Kenya",
		"create_new_batch": 0,
		"customer_code": "",
		"customer_items": [],
		"default_material_request_type": "Purchase",
		"delivered_by_supplier": 0,
		"description": "Waste Management Bill",
		"disabled": 0,
		"docstatus": 0,
		"doctype": "Item",
		"enable_deferred_expense": 0,
		"enable_deferred_revenue": 0,
		"end_of_life": "2099-12-31",
		"grant_commission": 1,
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"has_serial_no": 0,
		"has_variants": 0,
		"include_item_in_manufacturing": 1,
		"inspection_required_before_delivery": 0,
		"inspection_required_before_purchase": 0,
		"is_customer_provided_item": 0,
		"is_fixed_asset": 0,
		"is_item_from_hub": 0,
		"is_purchase_item": 1,
		"is_sales_item": 1,
		"is_stock_item": 0,
		"is_sub_contracted_item": 0,
		"item_code": "ITM-00004",
		"item_group": "Services",
		"item_name": "Waste Management Bill",
		"last_purchase_rate": 0.0,
		"lead_time_days": 0,
		"max_discount": 0.0,
		"min_order_qty": 0.0,
		"modified": "2022-10-04 14:30:43.329748",
		"name": "ITM-00004",
		"reorder_levels": [],
		"retain_sample": 0,
		"safety_stock": 0.0,
		"shelf_life_in_days": 0,
		"standard_rate": 0.0,
		"stock_uom": "Nos",
		"supplier_items": [],
		"synced_with_hub": 0,
		"taxes": [],
		"total_projected_qty": 0.0,
		"uoms": [
		{
			"conversion_factor": 1.0,
			"parent": "ITM-00004",
			"parentfield": "uoms",
			"parenttype": "Item",
			"uom": "Nos"
		}
		],
		"valuation_method": "",
		"valuation_rate": 0.0,
		"variant_based_on": "Item Attribute"
		},
		{
		"allow_alternative_item": 0,
		"attributes": [],
		"auto_create_assets": 0,
		"barcodes": [],
		"country_of_origin": "Kenya",
		"create_new_batch": 0,
		"customer_code": "",
		"customer_items": [],
		"default_material_request_type": "Purchase",
		"delivered_by_supplier": 0,
		"description": "Security Services Bill",
		"disabled": 0,
		"docstatus": 0,
		"doctype": "Item",
		"enable_deferred_expense": 0,
		"enable_deferred_revenue": 0,
		"end_of_life": "2099-12-31",
		"grant_commission": 1,
		"include_item_in_manufacturing": 1,
		"inspection_required_before_delivery": 0,
		"inspection_required_before_purchase": 0,
		"is_customer_provided_item": 0,
		"is_fixed_asset": 0,
		"is_item_from_hub": 0,
		"is_purchase_item": 1,
		"is_sales_item": 1,
		"is_stock_item": 0,
		"is_sub_contracted_item": 0,
		"item_code": "ITM-00005",
		"item_group": "Services",
		"item_name": "Security Services Bill",
		"last_purchase_rate": 0.0,
		"lead_time_days": 0,
		"max_discount": 0.0,
		"min_order_qty": 0.0,
		"modified": "2022-10-04 14:31:06.480056",
		"name": "ITM-00005",
		"no_of_months": 0,
		"no_of_months_exp": 0,
		"opening_stock": 0.0,
		"over_billing_allowance": 0.0,
		"over_delivery_receipt_allowance": 0.0,
		"reorder_levels": [],
		"retain_sample": 0,
		"safety_stock": 0.0,
		"shelf_life_in_days": 0,
		"standard_rate": 0.0,
		"stock_uom": "Nos",
		"supplier_items": [],
		"synced_with_hub": 0,
		"taxes": [],
		"total_projected_qty": 0.0,
		"uoms": [
		{
			"conversion_factor": 1.0,
			"parent": "ITM-00005",
			"parentfield": "uoms",
			"parenttype": "Item",
			"uom": "Nos"
		}
		],
		"valuation_method": "",
		"valuation_rate": 0.0,
		"variant_based_on": "Item Attribute"
		},
		{
		"allow_alternative_item": 0,
		"attributes": [],
		"auto_create_assets": 0,
		"barcodes": [],
		"country_of_origin": "Kenya",
		"create_new_batch": 0,
		"customer_code": "",
		"customer_items": [],
		"default_material_request_type": "Purchase",
		"delivered_by_supplier": 0,
		"description": "Internet Services Bill",
		"disabled": 0,
		"docstatus": 0,
		"doctype": "Item",
		"enable_deferred_expense": 0,
		"enable_deferred_revenue": 0,
		"end_of_life": "2099-12-31",
		"grant_commission": 1,
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"has_serial_no": 0,
		"has_variants": 0,
		"include_item_in_manufacturing": 1,
		"inspection_required_before_delivery": 0,
		"inspection_required_before_purchase": 0,
		"is_customer_provided_item": 0,
		"is_fixed_asset": 0,
		"is_item_from_hub": 0,
		"is_purchase_item": 1,
		"is_sales_item": 1,
		"is_stock_item": 0,
		"is_sub_contracted_item": 0,
		"item_code": "ITM-00006",
		"item_group": "Services",
		"item_name": "Internet Services Bill",
		"last_purchase_rate": 0.0,
		"lead_time_days": 0,
		"max_discount": 0.0,
		"min_order_qty": 0.0,
		"modified": "2022-10-04 14:31:30.019880",
		"name": "ITM-00006",
		"no_of_months": 0,
		"no_of_months_exp": 0,
		"opening_stock": 0.0,
		"over_billing_allowance": 0.0,
		"over_delivery_receipt_allowance": 0.0,
		"reorder_levels": [],
		"retain_sample": 0,
		"safety_stock": 0.0,
		"shelf_life_in_days": 0,
		"standard_rate": 0.0,
		"stock_uom": "Nos",
		"supplier_items": [],
		"synced_with_hub": 0,
		"taxes": [],
		"total_projected_qty": 0.0,
		"uoms": [
		{
			"conversion_factor": 1.0,
			"parent": "ITM-00006",
			"parentfield": "uoms",
			"parenttype": "Item",
			"uom": "Nos"
		}
		],
		"valuation_method": "",
		"valuation_rate": 0.0,
		"variant_based_on": "Item Attribute"
		},
		{
		"allow_alternative_item": 0,
		"country_of_origin": "Kenya",
		"create_new_batch": 0,
		"default_material_request_type": "Purchase",
		"delivered_by_supplier": 0,
		"description": "Security Deposit",
		"disabled": 0,
		"docstatus": 0,
		"doctype": "Item",
		"enable_deferred_expense": 0,
		"enable_deferred_revenue": 0,
		"end_of_life": "2099-12-31",
		"grant_commission": 1,
		"has_batch_no": 0,
		"has_expiry_date": 0,
		"has_serial_no": 0,
		"has_variants": 0,
		"include_item_in_manufacturing": 1,
		"inspection_required_before_delivery": 0,
		"inspection_required_before_purchase": 0,
		"is_customer_provided_item": 0,
		"is_fixed_asset": 0,
		"is_item_from_hub": 0,
		"is_purchase_item": 1,
		"is_sales_item": 1,
		"is_stock_item": 0,
		"is_sub_contracted_item": 0,
		"item_code": "ITM-00007",
		"item_group": "Services",
		"item_name": "Security Deposit",
		"last_purchase_rate": 0.0,
		"lead_time_days": 0,
		"max_discount": 0.0,
		"min_order_qty": 0.0,
		"modified": "2022-10-06 09:20:35.921914",
		"name": "ITM-00007",
		"no_of_months": 0,
		"no_of_months_exp": 0,
		"opening_stock": 0.0,
		"over_billing_allowance": 0.0,
		"over_delivery_receipt_allowance": 0.0,
		"sample_quantity": 0,
		"shelf_life_in_days": 0,
		"standard_rate": 0.0,
		"stock_uom": "Nos",
		"supplier_items": [],
		"synced_with_hub": 0,
		"taxes": [],
		"total_projected_qty": 0.0,
		"uoms": [
		{
			"conversion_factor": 1.0,
			"parent": "ITM-00007",
			"parentfield": "uoms",
			"parenttype": "Item",
			"uom": "Nos"
		}
		],
		"valuation_method": "",
		"valuation_rate": 0.0,
		"variant_based_on": "Item Attribute"
		}
	]
	frappe.db.set_value('Stock Settings', 'Stock Settings', 'item_naming_by', 'Item Code')
	for item in items:
		if not frappe.db.exists("Item", item.get('item_code'), cache=True):
			frappe.get_doc(item).insert()
	
	#UPDATE VALUES IN FACILITY SETTINGS
	frappe.db.set_value('Facility Management Settings', 'Facility Management Settings', 'rental_item', 'ITM-00001')
	frappe.db.set_value('Facility Management Settings', 'Facility Management Settings', 'deposit_item', 'ITM-00007')
		
	for company in frappe.db.get_all('Company'):
		payable_group_account = frappe.db.get_list('Account',
			filters={
				'account_name': 'Current Liabilities',
				'is_group': 1,
				'company': company.get('name')
			},
			fields=['name']
		)
		if not frappe.db.exists("Account", {"account_name": "Customer Deposits", "company": company.get('name')}):
			group_account = frappe.get_doc({
				"account_name": "Customer Deposits",
				"account_number": "2500",
				"balance_must_be": "",
				"disabled": 0,
				"docstatus": 0,
				"doctype": "Account",
				"freeze_account": "No",
				"include_in_gross": 0,
				"inter_company_account": 0,
				"is_group": 1,
				"parent": payable_group_account[0].name,
				"parent_account":  payable_group_account[0].name,
				"report_type": "Balance Sheet",
				"root_type": "Liability",
				"tax_rate": 0.0,
				"company": company.get('name')
			}).insert()
		else:
			group_account = frappe.db.get_list("Account", filters={"account_name": "Customer Deposits", "company": company.get('name')}, fields=['name'])[0]
		if not frappe.db.exists("Account", {"account_name": "Rent Security Deposit", "company": company.get('name')}):
			account = frappe.get_doc({
				"account_name": "Rent Security Deposit",
				"account_number": "2510",
				"balance_must_be": "",
				"disabled": 0,
				"docstatus": 0,
				"doctype": "Account",
				"freeze_account": "No",
				"include_in_gross": 0,
				"inter_company_account": 0,
				"is_group": 0,
				"parent": group_account.get('name'),
				"parent_account":  group_account.get('name'),
				"report_type": "Balance Sheet",
				"root_type": "Liability",
				"tax_rate": 0.0,
				"company": company.get('name')
			}).insert()
		else:
			account = frappe.db.get_list("Account", filters={"account_name": "Rent Security Deposit", "company": company.get('name')}, fields=['name'])[0]
		for item in items:
			if item.get('name') == 'ITM-00007':
				if not frappe.db.exists("Item Default", {'parent': item.get('name'), 'company': company.get('name')}):
					#CREATE IF NOT EXISTING.
					new_item_default = {
						"doctype": "Item Default",
						"parent": item.get('name'),
						"company": company.get('name'),
						"income_account": account.get('name'),
						"parentfield": "item_defaults",
						"parenttype": "Item"
					}
					frappe.get_doc(new_item_default).insert()
				else:
					for defaults in frappe.db.get_list('Item Default', filters={'parent': item.get('name'), 'company': company.get('name')}, fields={'*'}):
						frappe.db.set_value('Item Default', defaults.get('name'), 'income_account', account.get('name'))
